name: A4
channels:
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud//pytorch/
# - menpo
- defaults
dependencies:
- jupyter
- matplotlib
- python=3.8
- scikit-learn
- scikit-image
- scipy
- numpy
- cyvlfeat
- pip
- pip:
  - opencv-python
